// Generated by scripts/import-oddmenu.mjs from https://oddmenu.com/p/el-greco-seaview
// Do not edit by hand; re-run `npm run menu:import` instead.

import type { MenuData } from "@/lib/menu-types";

export const menuData: MenuData = {
  "source": "https://oddmenu.com/p/el-greco-seaview",
  "importedAt": "2026-09-25T19:01:08.563Z",
  "currency": "SLE",
  "place": {
    "name": "EL GRECO SEAVIEW",
    "phone": "+23299423234",
    "address": "63 Sir Samuel Lewis Road",
    "city": "Aberdeen",
    "country": "Sierra Leone"
  },
  "categories": [
    {
      "id": "cmmz3sgvo03u8vyfh3o10vuxs",
      "slug": "brunch",
      "name": "Brunch",
      "group": "brunch",
      "items": [
        {
          "id": "cmmz3yzc903v6vyfh3qr3moij",
          "name": "Benedict Classic",
          "description": "Two poached eggs, bacon/Turkey with hollandaise sauce",
          "price": 260,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz3tczn03ucvyfhzwjqf4m4",
          "name": "Pancake",
          "description": "Two eggs fried, bacon, pancake & fruits",
          "price": 280,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz3ugxt03ugvyfhmb0plcd4",
          "name": "Sunshine",
          "description": "Two fried eggs, bacon, crepe filled with cream & fruits",
          "price": 280,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz42vfl03vmvyfhagb3fs86",
          "name": "Veggie Omelette",
          "description": "Peppers, mushrooms, spinach, onions & waffles",
          "price": 240,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz40onb03vevyfhihi8zgf3",
          "name": "Cheese Omlet",
          "description": "Swiss cheese, white cheese & waffle",
          "price": 260,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz452yd03vqvyfh771ulx4v",
          "name": "Copenhagen Benedict",
          "description": "Two poached eggs, smoked salmon with hollandaise sauce",
          "price": 450,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz46orr03w2vyfhjxrndsoz",
          "name": "Elgreco Special",
          "description": "Two fried eggs, two waffle, bacon or Bresaola, cheese & fruits",
          "price": 320,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz483j903wavyfhaogyc4sx",
          "name": "Portobello Omelette",
          "description": "Prosciutto, mushrooms, pecorino romano cheese & waffle",
          "price": 280,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz48fo703wovyfhd0yjsif1",
          "name": "Cheese Pie",
          "price": 150,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz48xyd03wtvyfh9bkex5gb",
          "name": "Thyme Pie",
          "price": 100,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz496p003wxvyfhq0fng97g",
          "name": "Meat Pie",
          "price": 200,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz49ium03x5vyfhtn0ahhzb",
          "name": "Foul",
          "price": 250,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz49r8j03xavyfh86qf1yaz",
          "name": "Labneh",
          "price": 150,
          "available": true,
          "variants": [],
          "addons": []
        }
      ]
    },
    {
      "id": "cmmz3hkka03tfvyfhca28gfo5",
      "slug": "sandwiches",
      "name": "Sandwiches",
      "group": "mains",
      "items": [
        {
          "id": "cmmz3jmks03tjvyfh16aawuic",
          "name": "Scrambled Egg",
          "description": "Eggs, avocado, bresaola/ bacon, cheddar cheese, onions",
          "price": 240,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz3kvdy03tnvyfh9b417zgz",
          "name": "Quatro",
          "description": "Brie, swiss cheese, cheddar & blue cheese",
          "price": 285,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz3lpa103trvyfhr1kwdisc",
          "name": "Reuben",
          "description": "Bresaola, caramelized onions, swiss cheese & mustard",
          "price": 255,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz3mxox03tvvyfh2ra0mwvc",
          "name": "Greene Grilled",
          "description": "Cheddar, emmental, bacon, avocado & cilantro sauce",
          "price": 255,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz3nyxa03tzvyfhybg52ae5",
          "name": "Smoked Salom",
          "description": "Smoked salmon, brie cheese, swiss cheese, caramelized onions.",
          "price": 465,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz3q6xf03u5vyfh0d4rfgj1",
          "name": "Elgreco Special",
          "description": "Scrambled eggs, bacon, mix cheese, pickled peppers",
          "price": 265,
          "available": true,
          "variants": [],
          "addons": []
        }
      ]
    },
    {
      "id": "cmm2cwehl00qqwagjtnmez4ki",
      "slug": "african",
      "name": "African",
      "group": "specialities",
      "items": [
        {
          "id": "cmm2ddajx00r9wagj13wr7mde",
          "name": "Acheke & Jollof Platter",
          "description": "Steamed gari, Nigerian Jollof, fried chopped plaintains, vegetables, gravy, boiled egg with fried fish,chicken and goat meat(optional with additional cost of Le80)served with a bowl of fruits in season.",
          "price": 550,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmm3s10qy073qwagjety8o4x1",
          "name": "Yam Chips",
          "description": "Crispy fried yam served with spicy tomato sauce",
          "price": 180,
          "available": true,
          "variants": [],
          "addons": []
        }
      ]
    },
    {
      "id": "cmm2ab7fa00a0wagj27bxtdgq",
      "slug": "fast-food",
      "name": "Fast Food",
      "group": "mains",
      "items": [
        {
          "id": "cmm2aps0d00gkwagjvkucvvmw",
          "name": "Burger Squad (Beef)",
          "description": "Our sharable big bun beef burger with 4pcs chicken strips and golden fried french fries 2-4 people eat.",
          "price": 1100,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmm2avtnx00h0wagjy270i6gp",
          "name": "Burger Squad(Chicken)",
          "description": "Sharable big bun of chicken burger for 4 persons Server with a platter of french fries.",
          "price": 1050,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmm2aoh6r00g9wagjdrsn17no",
          "name": "Chicken Burger",
          "description": "Crispy fried chicken breast served a side of french fries",
          "price": 260,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmm2al99e00bnwagjloja39qs",
          "name": "Beef Burger",
          "description": "One layer of beef Served with a side of fries",
          "price": 260,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmm2aue7f00gwwagj735yh9rs",
          "name": "Fish Burger",
          "description": "Crispy fried fish fillet served with french fries",
          "price": 290,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmm2af03q00ajwagjwqyr6h8z",
          "name": "Chicken Wrap",
          "price": 185,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmm2agv1a00auwagjc7rm674w",
          "name": "Beef Wrap",
          "price": 240,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmm2aiimk00b5wagj5mflny4y",
          "name": "Shrimp Wrap",
          "price": 240,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmm2b1eku00hmwagj963bgvmv",
          "name": "Tawook Sandwich",
          "price": 190,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz2qf4i03rgvyfhmp4xerai",
          "name": "Wise 2",
          "description": "2 PCs of crispy fried chicken served with fried rice/ Fries and chilli pepper",
          "price": 190,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz2s8v303rovyfhinclrr3a",
          "name": "Wise 3",
          "description": "3 PCs of crispy fried chicken served with fried rice/fries",
          "price": 260,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz2tnqf03rwvyfhd4kp0iog",
          "name": "Wise 4",
          "description": "4 PCs Crispy fried chicken served with fried rice/fries",
          "price": 310,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz2ushq03s4vyfh9052jqug",
          "name": "Wise 5",
          "description": "5 PCs Crispy fried chicken served with one side dish",
          "price": 360,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz2wjs103sdvyfh1zwfzjkk",
          "name": "Family",
          "description": "10 PCs Crispy fried chicken served with two side dishes",
          "price": 680,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmz2xshs03shvyfhfc2yldfb",
          "name": "Combo",
          "description": "5 PCs of crispy fried chicken & 6 PCs of boneless strips",
          "price": 580,
          "available": true,
          "variants": [],
          "addons": []
        }
      ]
    },
    {
      "id": "clxga6fgc1209685dnl6c4hf6zzt",
      "slug": "appetizers",
      "name": "Appetizers",
      "group": "appetizers",
      "items": [
        {
          "id": "cmmjbcgwk021evy0ietg5xss6",
          "name": "Cheese Rolls",
          "description": "Mixed cheese with parsley flavored with sesame seeds",
          "price": 320,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmlztuxw70b5ewap4ln5fzivg",
          "name": "Trio Humus",
          "description": "3 flavors of homemade humus Traditional humus toped with 1 crispy homemade fried falafel Beetroot Humus mixed with the healthy grounded beetroot Chili humus is a mix of humus roasted red pepper and humus Served with our home crackers",
          "price": 490,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmlzuhuks0b75wap4ib0qa94d",
          "name": "Vegan Falafel",
          "description": "6 PCs of crispy fried humus paste mixed with fresh onions, garlic, parsley, coriander & the magical cummin powder Served with lebanese bread, tahini sauce, chili pepper sauce.",
          "price": 385,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmlzunlw20b7dwap4su3duoyx",
          "name": "Yam Chips",
          "description": "Nigerian yam sticks fried and flavored with butter garlic chili flakes served with chili pepper.",
          "price": 180,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmlzu2iqt0b67wap415jgo4on",
          "name": "Vine Leaves",
          "description": "6 PCs of homemade vegan Vine leaves stuffed with rice, parsley, onion and tomato slowly cooked with tomato sauce",
          "price": 265,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmlzu5s3z0b6gwap4gqavvx8r",
          "name": "Beetroot Humus",
          "description": "A special mix of humus and healthy grounded beetroot toped with beetroot slices & olive oil Served with lebanese bread.",
          "price": 300,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmlztjg4b0b56wap4ojgt57lx",
          "name": "Spicy Humus",
          "description": "A special spicy flavored humus with roasted red pepper blended together and served with lebanese bread",
          "price": 325,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxgak9ph1256246dnl6xseirwzh",
          "name": "Hummus",
          "description": "Traditional Lebanese hummus and fresh pita bread",
          "price": 270,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxgac1t91229316dnl6hpwl5uwq",
          "name": "Shrimp Dynamite",
          "description": "8pcs rock shrimps dressed with our special dynamite sauce",
          "price": 335,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmtrnwb9m08rbuhm01lcmqsmz",
          "name": "Spicy Wings🌶️🌶️🌶️",
          "description": "6 Crispy, juicy, and coated in our dangerously delicious spicy sauce.",
          "price": 220,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmj21bcu50ea3xbafyue0hxhs",
          "name": "Vegetable Samosa",
          "description": "Crispy pastry pockets filled with special potatoes and peas",
          "price": 225,
          "available": false,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmh1xjfbr06f3w3tc3c5hvg3q",
          "name": "Ceviche",
          "description": "Catch of the day ceviche(grouper/red snapper) - Bell pepper, red onion, grilled corn, cilantro, avocado, spring onions, grape fruit lache de tigre.",
          "price": 420,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxgay5fw1299461dnl6tz7avsxv",
          "name": "Bruschetta Smoked Salmon",
          "description": "Baguette bread with smoked salmon, cream cheese, lime fillet and spring onions",
          "price": 380,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmis4czu30pmoxbfcxcbirkpv",
          "name": "Fried Mina",
          "description": "1 dz fresh fried mina with fried pita bread, tahini sauce and a slice of lime.",
          "price": 265,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmis4blyj0pmcxbfcxfj41dom",
          "name": "Carpaccio",
          "description": "Raw catch of the day fish, capers, onion, ginger, lime, olives, spring onion, olive oil and grilled pineapple served with special bread",
          "price": 420,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxgahpbp1247216dnl65y8bdoe3",
          "name": "Vegetables Spring Rolls",
          "description": "Wrapped mix vegetables",
          "price": 290,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxgazusr1304967dnl6c3juag3c",
          "name": "Bruschetta Caprese",
          "description": "Baguette bread with tomatos and basil, olive oil and belsamic glaze",
          "price": 265,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cm06jz6ks333807p2l4lp5tbdsa",
          "name": "Mini Burgers",
          "description": "3pcs- our special mini chicken/beef burgers",
          "price": 220,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxgaltzk1260364dnl6eyyrjrom",
          "name": "Spicy Potato",
          "description": "Deep fried potato with cilantro",
          "price": 270,
          "available": true,
          "variants": [],
          "addons": []
        }
      ]
    },
    {
      "id": "clxg96bw91099844dnl69ud80o7h",
      "slug": "soups",
      "name": "Soups",
      "group": "appetizers",
      "items": [
        {
          "id": "clxgjdzlf379358dnl6iuz9y0x3",
          "name": "Sea Food Soup",
          "description": "Shrimps, calamari, baracuda dice in our special bouillabaisse soup",
          "price": 390,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxg96bwa1099848dnl6pa0i7ybd",
          "name": "Lentil Soup",
          "description": "A traditional mediterranean lentil soup",
          "price": 360,
          "weight": "250g",
          "available": true,
          "variants": [],
          "addons": []
        }
      ]
    },
    {
      "id": "clxg96bw71099807dnl656nyrcpe",
      "slug": "salads",
      "name": "Salads",
      "group": "appetizers",
      "items": [
        {
          "id": "clxgbog0t1381402dnl6taw0upin",
          "name": "Caesar Salad",
          "description": "Lettuce with ceasar salad dressing and grilled chicken with crouton and parmesan cheese",
          "price": 490,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxg96bw81099811dnl6201jw1nn",
          "name": "Smoked Salmon Salad",
          "description": "Lettuce, cucumber, pineapple, grapefruit, spring onions and our special sauce with salmon",
          "price": 650,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxgbg1cj1355624dnl60jfpq4yy",
          "name": "Fattouch",
          "description": "Tomatoes. Cucumber . Fried bread . Lettuce .red onion. Raddish . Sweet pepper with mint leaves",
          "price": 380,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxg96bw91099827dnl69irxxv8e",
          "name": "Greek Salad",
          "description": "Tomatoes, cucumber , red onions, fetta cheese.",
          "price": 360,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmb8mql6x0fr8xez14h0rfns6",
          "name": "Crunchy Quinoa (Vegan)",
          "description": "Cooked Quinoa, white onion, spring onion, sweet red and green pepper, grape fruit, cilantro, avocado with fried almond slices.",
          "price": 490,
          "available": true,
          "variants": [],
          "addons": []
        }
      ]
    },
    {
      "id": "clxiu0n081236238dml6khfe464v",
      "slug": "chicken",
      "name": "Chicken",
      "group": "mains",
      "items": [
        {
          "id": "clxiwky7g1461336dml6xlqr2fof",
          "name": "Grilled Chicken Plate",
          "description": "Grilled chicken served freid rice, plaintain and coleslaw",
          "price": 410,
          "prepMinutes": 20,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxiwib7d1455898dml68glrwurb",
          "name": "Tawook Plate",
          "description": "Marinated chicken skewers served with french fries, coleslaw, garlic paste, pickles and grilled pita bread",
          "price": 390,
          "prepMinutes": 15,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxiwh4l91452964dml68joj0kvb",
          "name": "Sweet and Sour Chicken",
          "description": "Chicken with sweet and sour sauce served with rice and plaintain",
          "price": 430,
          "prepMinutes": 15,
          "available": true,
          "variants": [],
          "addons": []
        }
      ]
    },
    {
      "id": "clxg96bwa1099854dnl6xaad0z7h",
      "slug": "pasta",
      "name": "Pasta",
      "group": "mains",
      "items": [
        {
          "id": "clxg96bwa1099858dnl6979071as",
          "name": "Chicken Alfredo",
          "description": "Home made Alfredo sauce with grilled breast chicken, topped with Parmesan cheese served with garlic bread.",
          "price": 430,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxiv5o7q1332302dml68pbsmjvs",
          "name": "Seafood Pasta",
          "description": "Pasta served with mix seafood in special tomato sauce",
          "price": 530,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxiv81i21339514dml6vum0p1ku",
          "name": "Stir Fried Noodles",
          "description": "Traditional asian egg noodles with chicken and mix vegetable",
          "price": 480,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmis3xozt0pk0xbfcti5l2elk",
          "name": "Bolognese Pasta",
          "description": "Famous beef rague served with spaghetti and parmesan cheese",
          "price": 450,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxg96bwa1099861dnl6209n7why",
          "name": "Arabiata",
          "description": "Penne pasta, with classic Italian ingredients like tomatoes, garlic, chili, olives and olive oil to make a spicy tomato sauce.",
          "price": 340,
          "available": true,
          "variants": [],
          "addons": [
            {
              "id": "clxg96b2t1099666dnl6he07abzk",
              "name": "Sauce",
              "selectType": "multi",
              "options": [
                {
                  "id": "clxg96b351099678dnl66j32e179",
                  "name": "Ketchup",
                  "price": 0.5
                },
                {
                  "id": "clxg96b341099676dnl6jplswoxl",
                  "name": "Barbeque",
                  "price": 0.5
                },
                {
                  "id": "clxg96b351099680dnl6txirj4r8",
                  "name": "Mustard",
                  "price": 0.5
                },
                {
                  "id": "clxg96b371099682dnl64fmrmknd",
                  "name": "Sweet and Sour",
                  "price": 0.5
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": "clxg96bwb1099864dnl613x2kefz",
      "slug": "beef-and-lamb",
      "name": "Beef & Lamb",
      "group": "mains",
      "items": [
        {
          "id": "cm437qbnb41946017lczvsb3457",
          "name": "T-Bone",
          "description": "A truly exceptional steak. This process concentrates the flavor and tenderizes the meat, resulting in a rich, buttery texture and an unforgettable beefy taste. Served with a side fries, fried rice or mashed potatoes",
          "price": 1600,
          "weight": "370g",
          "prepMinutes": 30,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxg96bwb1099867dnl6xqbln2sh",
          "name": "Tomahawk Steak (Spain)",
          "description": "Imported tomahawk steak with exiotic grilled vegetablees sedrved with mashed potato and cafe de paris sauce",
          "price": 1900,
          "weight": "650g",
          "prepMinutes": 25,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxg96bwb1099870dnl66mj17bxw",
          "name": "Ribeye Steak (Boran Kenyan)",
          "description": "Imported ribeye served with salad and fries and cafe de paris sauce",
          "price": 1800,
          "weight": "300g",
          "prepMinutes": 25,
          "available": false,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxg96bwb1099873dnl6somjagka",
          "name": "Lamb Skewers",
          "description": "Lamb beef kebab served with biwaz , homemade hummus, grilled onions & tomatos",
          "price": 625,
          "prepMinutes": 25,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmmasj28n01xiw40ifxm6hxxh",
          "name": "Mix Grill",
          "description": "1 skewer tawook 1 skewer goat meat 2 skewer kafta 1 skewer grilled veg served with side hummus, garlic paste, katch-up and french fries topped with spicy bread.",
          "price": 880,
          "available": true,
          "variants": [],
          "addons": []
        }
      ]
    },
    {
      "id": "clxiu2k7e1244221dml64np2qwjd",
      "slug": "seafood",
      "name": "Seafood",
      "group": "mains",
      "items": [
        {
          "id": "clxiwyi3z1496357dml6jtix4l3x",
          "name": "Seafood Platter",
          "description": "Grilled lobster+ shrimps+ grilled octopus leg+ mix seafood bowl-dips and fried rice on the side",
          "price": 2100,
          "prepMinutes": 35,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmj023fi50040xbaf5g9yzsk6",
          "name": "Seafood Jollof",
          "description": "Jollof Rice served with shrimp and octopus",
          "price": 505,
          "prepMinutes": 25,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cm0dfhcdb529484f5l4h0h8i2vl",
          "name": "Baked Tiger Prawns",
          "description": "Grilled tiger prawns served with fried rice, grilled exotic vegetables and boia bass dip",
          "price": 780,
          "prepMinutes": 20,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxiwt1xr1480187dml6ulah571r",
          "name": "Grilled Fish",
          "description": "Grilled catch of the day served with fried rice, plaintain and grilled exotic vegetables",
          "price": 575,
          "weight": "+250gr",
          "prepMinutes": 25,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxiwzxt01499426dml6rzs8irrw",
          "name": "Grilled Lobster",
          "description": "Grilled lobster served with fried rice and exotic grilled vegetables with bouillabaisse sauce",
          "price": 1020,
          "prepMinutes": 25,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxix1mpm1504709dml60ab7wk6w",
          "name": "Grilled Shrimps",
          "description": "10 pcs of grilled shrimps served with rice and plaintain and mix vegetables",
          "price": 575,
          "prepMinutes": 20,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxiwvtii1489407dml6gxz7w2gm",
          "name": "Seared Barracuda",
          "description": "Seared barracuda served with fried rice with exotic grilled vegetables, plaintain and cafe de paris sauce",
          "price": 550,
          "prepMinutes": 20,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmius8ytk07cixbtlki4ju6wt",
          "name": "Seaview Special",
          "description": "Octopus Legs, Garlic flacks, Glazed teriyaki, Mashed sweet Potato",
          "price": 430,
          "prepMinutes": 20,
          "available": false,
          "variants": [],
          "addons": []
        }
      ]
    },
    {
      "id": "clxixrgxn1579652dml6wjpq9m3b",
      "slug": "pizza",
      "name": "Pizza",
      "group": "mains",
      "items": [
        {
          "id": "cmiurn3hj075pxbtlsuv9a92j",
          "name": "Beef Pizza",
          "description": "Pizza sauce, mozarella cheese, ground beef, chilli powder",
          "price": 380,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxiy20bq1607223dml6div4psp8",
          "name": "Seafood Pizza",
          "description": "Pizza sauce - mozarrela - calamari - shrimps",
          "price": 390,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxiy0gd01603329dml6ua8yt45z",
          "name": "Margarita",
          "description": "Pizza sauce - mozarella - slice tomatos",
          "price": 300,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxiy2rvr1609552dml6g73zstlo",
          "name": "Peperoni",
          "description": "Pizza sauce - mozarella - peperoni",
          "price": 355,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxiy56mn1615518dml6lr7xh9ii",
          "name": "Smoked Salmon Pizza",
          "description": "Pizza sauce - mozarella - smoked salmon - capers",
          "price": 505,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxixu6f91587516dml6uyvuetnk",
          "name": "Chicken Pizza",
          "description": "Pizza sauce - chicken - mashroom - mozarella - bbq sauce",
          "price": 340,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxiy45it1612822dml6bgguyy1e",
          "name": "Quatro Chesse",
          "description": "Pizza sauce - mozarella - goda cheese -emantal cheese- blue cheese",
          "price": 345,
          "available": true,
          "variants": [],
          "addons": []
        }
      ]
    },
    {
      "id": "cmj1tsjuv0cmwxbafer6agqik",
      "slug": "indian",
      "name": "Indian",
      "group": "specialities",
      "items": [
        {
          "id": "cmj1u989n0ct1xbafh6lvav11",
          "name": "Chicken Korma Masala",
          "description": "Tender Chicken cooked in a creamy ,mildly spiced masala sauce served with basmati rice",
          "price": 430,
          "prepMinutes": 20,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmj1uh4ca0cumxbafx7tfytv4",
          "name": "Paneer Tikka Masala",
          "description": "Grilled paneer cubes cooked in a creamy mildly spicy tomato masala with aromatic herbs served with basmati rice",
          "price": 430,
          "prepMinutes": 15,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmj1zsd8q0e3pxbafogbsfync",
          "name": "Palak Paneer",
          "description": "Soft cubes of Paneer in a mildly spiced spinach sauce. Served with Basmati rice or Naan",
          "price": 410,
          "prepMinutes": 20,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmj20cmhd0e7wxbaf4kazypkd",
          "name": "Rumali Roti",
          "description": "Thin, soft Indian flatbread, perfect with curries",
          "price": 110,
          "prepMinutes": 10,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmj20etkt0e85xbafsc477ofi",
          "name": "Butter Naan",
          "description": "Soft, fluffy Indian flatbread brushed with butter. Perfect with curries or gravies",
          "price": 110,
          "prepMinutes": 10,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmj206n3g0e6ixbafx4phmhs1",
          "name": "Soya Biryani",
          "description": "Aromatic basmati rice with spiced soya chunks. Servede with raita",
          "price": 455,
          "prepMinutes": 20,
          "available": true,
          "variants": [],
          "addons": []
        }
      ]
    },
    {
      "id": "clxiu9m5o1262195dml66jxlq3af",
      "slug": "desserts",
      "name": "Desserts",
      "group": "desserts",
      "items": [
        {
          "id": "cm6b2a2ov6745785sqicj8drki8",
          "name": "Croissant",
          "description": "Plain",
          "price": 75,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cm6b2bg6l6759685sqim558461s",
          "name": "Cossiant",
          "description": "Chocolate",
          "price": 90,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cm6b2rkax6927405sqil64ae979",
          "name": "Banana Bread",
          "price": 55,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cm6b1wmsx6614195sqicuk8f9i4",
          "name": "Donut",
          "description": "Plain",
          "price": 55,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cm6b2wmwi6968025sqim8mg2kw9",
          "name": "Lazy Cake",
          "price": 180,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cm6b4vzxy7660125sqi72uigz2w",
          "name": "Swiss Roll",
          "price": 120,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxx824hh150022b4l6ogvr6edy",
          "name": "Waffle",
          "price": 0,
          "available": true,
          "variants": [
            {
              "id": "clxx824hi150029b4l6m4kz2j9t",
              "name": "Chocolate Fondue",
              "price": 120
            },
            {
              "id": "clxx824hi150032b4l6d0ngpauk",
              "name": "Chocolate Banana",
              "price": 120
            },
            {
              "id": "clxx824hi150035b4l68b8d9xhh",
              "name": "Choco Loce",
              "price": 120
            },
            {
              "id": "clxx824hi150038b4l66neclt92",
              "name": "Oreo",
              "price": 160
            },
            {
              "id": "clxx824hi150041b4l6d93ft9rl",
              "name": "Lotus",
              "price": 160
            }
          ],
          "addons": []
        },
        {
          "id": "clxx8dkg4175823b4l6l7vxma43",
          "name": "Crepe",
          "price": 0,
          "available": true,
          "variants": [
            {
              "id": "clxx8dkg5175833b4l6ha7qo6d6",
              "name": "Chocolate Banana",
              "price": 160
            },
            {
              "id": "clxx8dkg5175842b4l60oyjuq47",
              "name": "Oreo",
              "price": 160
            },
            {
              "id": "clxx8dkg5175845b4l6feftybi5",
              "name": "Lotus",
              "price": 160
            }
          ],
          "addons": [
            {
              "id": "clxx8cmt4173638b4l6s6u8xzzz",
              "name": "Topping",
              "selectType": "single",
              "options": [
                {
                  "id": "clxx8cmtg173647b4l6e61bkd1y",
                  "name": "Kitkat",
                  "price": 25
                },
                {
                  "id": "clxx8cmtg173649b4l6k6cc6zue",
                  "name": "Oreo",
                  "price": 25
                },
                {
                  "id": "clxx8cmtg173651b4l62m3dq2m4",
                  "name": "Smarties",
                  "price": 25
                },
                {
                  "id": "clxx8cmtg173654b4l6yo0f7efd",
                  "name": "Marshmallows",
                  "price": 25
                },
                {
                  "id": "clxx8cmtg173656b4l68qw8q4kn",
                  "name": "Ice Cream",
                  "price": 45
                }
              ]
            }
          ]
        },
        {
          "id": "clxx8tw55213954b4l6308r1rab",
          "name": "Ice Cream",
          "description": "Vanilla ice cream served with a waffle and 1 toppinng",
          "price": 90,
          "available": true,
          "variants": [],
          "addons": [
            {
              "id": "clxx8tqrp213494b4l64clet0vh",
              "name": "Topping",
              "selectType": "single",
              "options": [
                {
                  "id": "clxx8tqs5213503b4l6cbvnzb3k",
                  "name": "Oreo",
                  "price": 25
                },
                {
                  "id": "clxx8tqs6213509b4l6uq1ixepi",
                  "name": "Marshmellows",
                  "price": 25
                },
                {
                  "id": "clxx8tqs5213505b4l6k1nd1ekd",
                  "name": "Kitkat",
                  "price": 25
                },
                {
                  "id": "clxx8tqs6213507b4l6ry5ixjt1",
                  "name": "Smarties",
                  "price": 25
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": "clxg96bwe1099881dnl6dsc6mldr",
      "slug": "soft-drinks",
      "name": "Soft Drinks",
      "group": "drinks",
      "items": [
        {
          "id": "clxg96bwe1099885dnl6thcileqc",
          "name": "Coca Cola",
          "price": 60,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxg96bwf1099898dnl6dq1skavj",
          "name": "Fanta",
          "price": 60,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhkii7o60555e2l6jy9sm6wa",
          "name": "Sprite",
          "price": 60,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhkj6yj63091e2l6tmm3wdfz",
          "name": "Cocca Cola Light",
          "price": 70,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhkk2ai65941e2l6ss71kj8t",
          "name": "Maltina",
          "price": 70,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhkl19469265e2l68gfyuujr",
          "name": "Vody",
          "price": 75,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhklaus70350e2l60pm0pd36",
          "name": "Vimto",
          "price": 70,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhl986o140452e2l6e72n1b6x",
          "name": "Sparkling Water 50cl",
          "price": 110,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhla4np143318e2l67gkkktup",
          "name": "Sparkling Water 33cl",
          "price": 95,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhlbvki147718e2l6161o5q7s",
          "name": "Sparkling 75cl",
          "price": 175,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhldmjt151889e2l6l8kwv3a5",
          "name": "Stiil Water 75 cl",
          "price": 115,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhleqkd155258e2l60zrffa9y",
          "name": "Imported Water",
          "price": 60,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhljwcc169204e2l6o2l1yvk3",
          "name": "Ginger 20 cl",
          "price": 95,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhll7ec172065e2l6ytphhpgt",
          "name": "Lemonade 20cl",
          "price": 95,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhllk4f172838e2l6o6k8hk6j",
          "name": "Tonic 20 cl",
          "price": 95,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmofv54lu03w0xjmpqbxrc4n9",
          "name": "Ginger Beer",
          "price": 50,
          "available": true,
          "variants": [],
          "addons": []
        }
      ]
    },
    {
      "id": "clxg96bwf1099911dnl6jcti9gel",
      "slug": "beer",
      "name": "Beer",
      "group": "drinks",
      "items": [
        {
          "id": "clxg96bwg1099914dnl6y2s5md3s",
          "name": "Heineken",
          "price": 110,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxg96bwg1099917dnl6vs5pol1f",
          "name": "Guinness",
          "price": 100,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxg96bwg1099920dnl68h6yf6zr",
          "name": "Becks",
          "price": 110,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhn3hzz320195e2l6rpuzj8xg",
          "name": "Mexican Beer",
          "price": 120,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmj3ddoqb03qqw10iejobudma",
          "name": "Corona",
          "price": 120,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cmj3dg2pi03qzw10ihazm2iqf",
          "name": "Budweiser",
          "price": 120,
          "available": true,
          "variants": [],
          "addons": []
        }
      ]
    },
    {
      "id": "clxg96bwg1099923dnl6tuswp15j",
      "slug": "mocktails",
      "name": "Mocktails",
      "group": "drinks",
      "items": [
        {
          "id": "clxg96bwg1099926dnl6afnocxc0",
          "name": "Virgin Mojito",
          "price": 160,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxg96bwg1099929dnl69jdqchbg",
          "name": "Frozen Bellini",
          "price": 200,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxho167f423466e2l6cnwve3ji",
          "name": "V Passion Fruit Mojito",
          "price": 180,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxho1jbv424994e2l6jfapt4bv",
          "name": "V Pinacolada",
          "price": 180,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxho2232426190e2l61bns4fye",
          "name": "V.Strawberry Mojito",
          "price": 170,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkpjnqt416733wal6ixig0axa",
          "name": "Mango Smoothie",
          "price": 120,
          "available": true,
          "variants": [],
          "addons": []
        }
      ]
    },
    {
      "id": "clxhk9c2335184e2l6geyiljtl",
      "slug": "cocktails",
      "name": "Cocktails",
      "group": "drinks",
      "items": [
        {
          "id": "cm6b14vpl6335015sqio6wc82rv",
          "name": "Pink Lady",
          "price": 300,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxho394m429655e2l6gnq2ifse",
          "name": "Aperol Spritz",
          "price": 300,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxho47la432632e2l60ebub1yx",
          "name": "Classic Margarita",
          "price": 250,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxho4jlc433972e2l6npj61z2q",
          "name": "Cosmopolitan",
          "price": 250,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxho58ki436207e2l6m8lpfrmf",
          "name": "Lemon Daiquiri",
          "price": 200,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxho5wji438397e2l6nznev3uc",
          "name": "Mojito",
          "price": 250,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxho6iah439723e2l65lvn3suv",
          "name": "Strawberry Daiquiri",
          "price": 250,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxho6tzr440943e2l63wv6f0ya",
          "name": "Gin Basil",
          "price": 250,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxho76qc442154e2l6ycy4zioa",
          "name": "Long Island",
          "price": 300,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxho8csm445813e2l62us81vtm",
          "name": "Pinacolada",
          "price": 200,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxho8pif447101e2l6ey2esey7",
          "name": "Sex on the Beach",
          "price": 250,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxho97ag448344e2l65s9g1ri8",
          "name": "Dirty Martiny",
          "price": 250,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxj0cmf8148789dml6958zf77g",
          "name": "Old Fashion",
          "price": 250,
          "available": true,
          "variants": [],
          "addons": []
        }
      ]
    },
    {
      "id": "clxhk9jwo35988e2l6nvguj13c",
      "slug": "spirits-and-wine",
      "name": "Spirits & Wine",
      "group": "drinks",
      "items": [
        {
          "id": "clxhoa5ag450707e2l67b780vyb",
          "name": "Absolut Shot",
          "price": 100,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhoaiam451320e2l6mmmu21c2",
          "name": "Black Label Shot",
          "price": 125,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhoaxq7452245e2l6oxssehq2",
          "name": "Captain Morgan Shot",
          "price": 120,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhob9av452980e2l6dp7to7qe",
          "name": "Double Black Glass",
          "price": 320,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhobt7r454335e2l6fnzrourt",
          "name": "Gold Label Glass",
          "price": 370,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhoc58v455294e2l6ge28lchx",
          "name": "Jack Daniels Glass",
          "price": 250,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhp43zm546035e2l6mxsm7ifw",
          "name": "Jameson Shot",
          "price": 150,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhocloe456435e2l6d7adtk1j",
          "name": "Martini Shot",
          "price": 90,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhod0nz457935e2l6n7fnyqsc",
          "name": "Prosseco Glass",
          "price": 180,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhodecy459212e2l60ym2ctms",
          "name": "Red Label Shot",
          "price": 100,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhodtwr461143e2l6lvsjklxx",
          "name": "Remy Martin Glass",
          "price": 430,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhoeqnn464644e2l6tv4z5ud7",
          "name": "White Wine Glass",
          "price": 150,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhof1h5465449e2l62yavqxxm",
          "name": "Red Whine Glass",
          "price": 150,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhofdkz466800e2l6vgvd2lcw",
          "name": "Tekila White Shot",
          "price": 100,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhog15u469917e2l6oz5439jn",
          "name": "Tekila Gold Shot",
          "price": 150,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "cm2uyonve387916v2rt9wbhge3r",
          "name": "Patron Shot",
          "price": 200,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxhoh3d9474689e2l6icq7bebz",
          "name": "Jagermaster Shot",
          "price": 120,
          "available": true,
          "variants": [],
          "addons": []
        }
      ]
    },
    {
      "id": "clxkoqkin322946wal6poahhts0",
      "slug": "hot-beverages",
      "name": "Hot Beverages",
      "group": "drinks",
      "items": [
        {
          "id": "clxkosqbw329753wal65xaagc01",
          "name": "Americano",
          "price": 95,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkot24q330881wal6yy88bq7a",
          "name": "Caffe Latte",
          "price": 110,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkotpw1333078wal6j3xw6q87",
          "name": "Caffe Mocha ( Choclate )",
          "price": 120,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkoudzu334915wal6zc4l5lxj",
          "name": "Cappuccino",
          "price": 110,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkouq3u335932wal6lq6fxicc",
          "name": "Caramel Latte",
          "price": 110,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkov1z8337056wal60xu998dr",
          "name": "Matcha Latte",
          "price": 250,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkovp9g339184wal6bk96q89i",
          "name": "Flat White",
          "price": 110,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkowez6341529wal6cmpmc5n1",
          "name": "Espresso Double",
          "price": 85,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkowolf342319wal6nk1gwtxz",
          "name": "Espresso",
          "price": 60,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkoxdjr344818wal6sqote1kx",
          "name": "Classic Hot Choclate",
          "price": 95,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkoy9i2347450wal6j2pcsva4",
          "name": "Tea",
          "price": 60,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkoyv09349692wal66t7ho9eo",
          "name": "Vanilla Latte",
          "price": 110,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkozioh352103wal6ujqcxpqz",
          "name": "Cafe Mocha (White )",
          "price": 120,
          "available": true,
          "variants": [],
          "addons": []
        }
      ]
    },
    {
      "id": "clxkp0fak355271wal6ffpgsr8h",
      "slug": "iced-beverages",
      "name": "Iced Beverages",
      "group": "drinks",
      "items": [
        {
          "id": "clxkp1uka360716wal6qpe667js",
          "name": "Americano Ice",
          "price": 120,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkp414b368221wal6548ialqp",
          "name": "Cafe Latte Iced",
          "price": 140,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkp4ipx369925wal62abuzo1c",
          "name": "Caramel Latte Iced",
          "price": 140,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkp50vp371306wal6nvdknk4b",
          "name": "Caramel Macciatho Iced",
          "price": 140,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkp5fld372309wal674bxv2zx",
          "name": "Chocolate Iced",
          "price": 120,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkp5uxc373513wal6wna5rjgz",
          "name": "Vanilla Latte Iced",
          "price": 140,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkp6ivn375135wal6a7ugvkc5",
          "name": "Mocha Iced (Choclate)",
          "price": 160,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkp7k3v377826wal6cdvmqdz6",
          "name": "Matcha Latte Iced",
          "price": 250,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkp8nil380902wal6dthokt91",
          "name": "Iced Tea",
          "price": 95,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkp8z8m381717wal6331j3pbo",
          "name": "Cold Brew",
          "price": 100,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkp9r9s383812wal6uf2v2kwp",
          "name": "Mocha Iced (White)",
          "price": 160,
          "available": true,
          "variants": [],
          "addons": []
        }
      ]
    },
    {
      "id": "clxkpakrn386778wal6fjamqi4q",
      "slug": "milkshakes",
      "name": "Milkshakes",
      "group": "drinks",
      "items": [
        {
          "id": "clxkpcvbt393849wal6j0vntjsk",
          "name": "El Greco Special Shake",
          "price": 200,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkpdgnr395694wal6irpxxdbi",
          "name": "Lotus Shake",
          "price": 170,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkpdu2e397325wal62h2bo812",
          "name": "Oreo Shake",
          "price": 170,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkpe8gy398616wal6hwq2flwo",
          "name": "Strawberry Shake",
          "price": 170,
          "available": true,
          "variants": [],
          "addons": []
        }
      ]
    },
    {
      "id": "clxkpg3as404402wal6v3g2s4ta",
      "slug": "frappes",
      "name": "Frappés",
      "group": "drinks",
      "items": [
        {
          "id": "clxkpgk6t405583wal6vmvvz2g9",
          "name": "Caramel",
          "price": 140,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkph0iv406816wal6r5pge4cc",
          "name": "El Greco Special",
          "price": 180,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkphfmk408759wal64ie6g671",
          "name": "Espresso",
          "price": 140,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkpht2q410173wal6rb8pcrd8",
          "name": "Matcha Cream",
          "price": 240,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkpi6n4411422wal65c1wdzby",
          "name": "Mocha",
          "price": 140,
          "available": true,
          "variants": [],
          "addons": []
        },
        {
          "id": "clxkpijdy412347wal6ygtgu98e",
          "name": "Vanilla",
          "price": 140,
          "available": true,
          "variants": [],
          "addons": []
        }
      ]
    }
  ]
};
